%% Part 4 — Forecast evaluation against a linear AR benchmark
% We compare one-step-ahead forecasts generated by the SETAR model against
% a linear AR(1) fit. Both in-sample and out-of-sample accuracy metrics are
% reported along with diagnostic visualisations.

clear; close all; clc;
addpath(fullfile(fileparts(mfilename('fullpath')), 'functions'));

[folder, ~, ~] = fileparts(mfilename('fullpath'));
dataFile = fullfile(folder, 'data', 'part1_sim.mat');
modelFile = fullfile(folder, 'results', 'part2_model.mat');
assert(exist(dataFile, 'file') == 2 && exist(modelFile, 'file') == 2, ...
    'Run part1.m and part2.m before part4.m');

Sdata = load(dataFile);
y = Sdata.y;
Smodel = load(modelFile);
model = Smodel.model;

%% Prepare
T = numel(y);
pLow = numel(model.coeffLow) - 1;
pHigh = numel(model.coeffHigh) - 1;
delay = model.delay;
maxLag = max([pLow, pHigh, delay]);

%% In-sample SETAR forecasts
setarPred = nan(T, 1);
for t = maxLag + 1:T
    history = y(1:t-1);
    setarPred(t) = setar_forecast(history, model, 1);
end
setarResid = y(maxLag+1:end) - setarPred(maxLag+1:end);
rmseSetar = sqrt(mean(setarResid.^2));

%% Linear AR(1) benchmark
arModel = fit_ar_ls(y, 1);
phi = arModel.coeff(2);
const = arModel.coeff(1);
arPred = nan(T, 1);
for t = 2:T
    arPred(t) = const + phi * y(t-1);
end
arResid = y(2:end) - arPred(2:end);
rmseAR = sqrt(mean(arResid.^2));

%% Rolling out-of-sample evaluation (last 200 observations)
holdout = min(200, T - maxLag - 10);
startEval = T - holdout + 1;
setarOOS = nan(holdout,1);
arOOS = nan(holdout,1);
actual = y(startEval:end);

for k = 1:holdout
    t = startEval + k - 1;
    history = y(1:t-1);
    setarOOS(k) = setar_forecast(history, model, 1);
    arOOS(k) = const + phi * y(t-1);
end

oosRmseSetar = sqrt(mean((actual - setarOOS).^2));
oosRmseAr = sqrt(mean((actual - arOOS).^2));

%% Save metrics
resultFile = fullfile(folder, 'results', 'part4_forecast_metrics.txt');
fid = fopen(resultFile, 'w');
fprintf(fid, 'In-sample RMSE SETAR: %.4f\n', rmseSetar);
fprintf(fid, 'In-sample RMSE AR(1): %.4f\n', rmseAR);
fprintf(fid, 'Out-of-sample RMSE SETAR: %.4f\n', oosRmseSetar);
fprintf(fid, 'Out-of-sample RMSE AR(1): %.4f\n', oosRmseAr);
fclose(fid);

disp('--- Part 4 forecast metrics ---');
disp(fileread(resultFile));

%% Visual comparison on holdout window
figDir = fullfile(folder, 'figs');
if exist(figDir, 'dir') ~= 7
    mkdir(figDir);
end

figure('Name', 'Part 4 forecasts', 'Color', 'w');
tHold = (startEval:T)';
plot(tHold, actual, 'k-', 'LineWidth', 1.1, 'DisplayName', 'Actual'); hold on;
plot(tHold, setarOOS, 'r-', 'LineWidth', 1.1, 'DisplayName', 'SETAR forecast');
plot(tHold, arOOS, 'b--', 'LineWidth', 1.1, 'DisplayName', 'AR(1) forecast');
grid on; xlabel('t'); ylabel('$y_t$', 'Interpreter', 'latex');
title('Out-of-sample one-step forecasts', 'Interpreter', 'latex');
legend('Location', 'best');

print('-dpng', fullfile(figDir, 'part4_forecasts.png'));
